name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    container: noki3138/rust-cc-container:version1.0

    steps:
    - uses: actions/checkout@v3
    - name: Build & test
      run: |
        cargo test --verbose
        cargo build --target x86_64-unknown-linux-gnu --target x86_64-pc-windows-gnu --release --verbose
        mkdir out
        cp target/x86_64-unknown-linux-gnu/release/anibebra out/anibebra-linux
        cp target/x86_64-pc-windows-gnu/release/anibebra.exe out/anibebra-win.exe
    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Автоматический релиз"
        description: "Автоматически собранный релиз на все платформы после пуша в ветку main"
        files: |
          out/anibebra-linux
          out/anibebra-win.exe
